# Generated by Django 3.2.8 on 2021-10-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoAPI', '0005_auto_20211023_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='FD',
            field=models.IntegerField(verbose_name='feed capacity (kilogram)'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='MTDE',
            field=models.FloatField(verbose_name='Motor drive-end temperature reading (degrees Celsius)'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='MVDEA',
            field=models.FloatField(verbose_name='Motor drive-end axial velocity (metre per second)'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='MVDEH',
            field=models.FloatField(verbose_name='Motor drive-end vertical velocity (metre per second)'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='MVDEV',
            field=models.FloatField(verbose_name='Motor drive-end horizontal velocity (metre per second)'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='STDE',
            field=models.FloatField(verbose_name=' Shaft drive-end temperature reading (degrees Celsius)'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='SUDEC',
            field=models.IntegerField(verbose_name='Shaft drive-end carpet decibel reading (decibels)'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='SUDEM',
            field=models.IntegerField(verbose_name='Shaft drive-end maximum decibel reading (decibels)'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='SVDEH',
            field=models.FloatField(verbose_name='Shaft drive-end horizontal velocity (metre per second)'),
        ),
        migrations.AlterField(
            model_name='surveyor',
            name='SVDEV',
            field=models.FloatField(verbose_name='Shaft drive-end vertical velocity (metre per second)'),
        ),
    ]
